[build-system]
requires = ["pybind11 @ git+https://github.com/pybind/pybind11.git@master", 
			"setuptools @ git+https://github.com/pypa/setuptools.git@main"]
build-backend = "setuptools.build_meta"